object MenuForm: TMenuForm
  Left = 218
  Top = 238
  BorderStyle = bsNone
  ClientHeight = 115
  ClientWidth = 169
  Color = 13138366
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  PixelsPerInch = 96
  TextHeight = 13
end
